services:
  web:
    build: ./app
    restart: unless-stopped
    container_name: flask_portfolio
    env_file:
      - ./app/.env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
